---
title: "Participant characteristics"
author: "baf44"
date: "12/8/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Setup

```{r load packages }
# load packages
library(data.table)
library(boot) 
library(table1)
library(ggplot2)
library(dplyr)
library(haven)
library(reshape2)
```

```{r source data}

# Source gen_V6_covariates.R to generate pre-MRI fullness variables
  # this sources data_org.R to generate censor_sum and V6_compiled datasets 
  # will create 'compiled' database that is V6_compiled + pre_mri_ff and pre_mri_snack variables
  # will generate a dataframe called ff_concat that contains imputed values for subject 54

source("R/gen_V6_covariates.R")

```

# Prepare dataframes

```{r generate demo variables}

#### Income ####
# orig coding (0'<$20K' 1'$20-35,999K' 2'$36-50,999K' 3'$51-75,999K' 4'$76-100K' 5'>$100K')

# make income_recode variable with 3 brackets: >51k, 51-100k, >100k
compiled$income_recode <- NA
compiled$income_recode[compiled$income < 3] <- 0
compiled$income_recode[compiled$income == 3 ] <- 1
compiled$income_recode[compiled$income == 4 ] <- 1
compiled$income_recode[compiled$income == 5 ] <- 2

compiled$income_recode <- factor(compiled$income_recode, levels=c(0,1,2),
         labels=c("< $51,000K", 
                  "51-100K",
                  "> $100K"))

#### Maternal education ####
# Make maternal education variable based on parent_ed and parent_respondent
compiled$mom_edu <- NA
compiled$mom_edu_other <- NA
for (i in 1:nrow(compiled)) {
  if((compiled$parent_respondent[i] == 0)) {
    compiled$mom_edu[i] <- compiled$parent_ed[i]
    compiled$mom_edu_other[i] <- compiled$parent_ed_other[i]
  }
  else {
    compiled$mom_edu[i] <- compiled$partner_ed[i]
    compiled$mom_edu_other[i] <- compiled$partner_ed_other[i]
  }
}

# Original levels: (0=HighSchool,  1=Associates, 2=Technical, 3=Bachelors, 4=masters, 5=PhD, 6=MD, 7=JD, 8=Other)

# Create new maternal education variable with 3 levels (0= >BA, 1=BA, 2=>BA, 3=other)
compiled$mom_edu_recode <- NA
compiled$mom_edu_recode[compiled$mom_edu < 3] <- 0
compiled$mom_edu_recode[compiled$mom_edu == 3 ] <- 1
compiled$mom_edu_recode[compiled$mom_edu > 3 & compiled$mom_edu < 8 ] <- 2
#compiled$mom_edu_recode[compiled$mom_edu == 8 ] <- 3 #there are no "Other"s
compiled$mom_edu_recode <- factor(compiled$mom_edu_recode, levels=c(0,1,2),
         labels=c("< BA", 
                  "BA",
                  "> BA"))

#### Maternal BMI ####
compiled$mom_bmi <- NA
compiled$mom_bmi_method <- NA
for (i in 1:nrow(compiled)) {
  if((compiled$parent_respondent[i] == 0)) {
    compiled$mom_bmi[i] <- compiled$parent_bmi[i] #parent_bmi is from measured height/weight
    compiled$mom_bmi_method[i] <- "measured"
  }
  else {
    compiled$mom_bmi[i] <- compiled$sr_mom_bmi[i] #sr_mom_bmi is from self-report height/weight
    compiled$mom_bmi_method[i] <- "reported"
  }
}

#### Fat mass index 
compiled$dxa_total_fat_mass <- as.numeric(compiled$dxa_total_fat_mass)
compiled$fmi <- (compiled$dxa_total_fat_mass / 1000) / ((compiled$height_avg * 0.01)^2)
```

```{r generate MRI variables}
#### assess exclusion rationale ####
# count the number of food cue runs initiated per subject
compiled$n_run_complete <- rowSums(compiled[ , c("fmri_pp_scans_roar___2","fmri_pp_scans_roar___3", "fmri_pp_scans_roar___4","fmri_pp_scans_roar___5","fmri_pp_scans_roar___6")])

# count the number of runs per subject with less than 20% of interest_TRs censored
run_count <- censor_sum %>% group_by(id) %>% dplyr::summarise(n_run_good = sum(p_censor_interest < 20))

# add run_count to attended_v6
compiled<-merge(x=compiled,y=run_count,by="id",all.x=TRUE)

# make variable for exclusion rationale
compiled$exc_rationale <- NA

for (i in 1:nrow(compiled)) {
  if(compiled$fmri_pp_complete[i] == 0) {
    compiled$exc_rationale[i] <- "withdrew from MRI"
  }
  else if(compiled$n_run_complete[i] <3) {
    compiled$exc_rationale[i] <- "withdrew <3 runs"
  }
  else if(compiled$n_run_good[i] < 3) {
    compiled$exc_rationale[i] <- "motion"
  }
  else if(compiled$id[i] == 105 | compiled$id[i] == 119) {
    compiled$exc_rationale[i] <- "FOV"
  }
  else if(compiled$id[i] == 31) {
    compiled$exc_rationale[i] <- "inelligible - ADHD"
  }
}


#### calculate number of time points included in analyses ####

# subset dataframe to "good runs" only
censor_sum_goodruns <- censor_sum[censor_sum$p_censor_interest < 20, ]

# get number of volumes included (not censored) for each run
censor_sum_goodruns$n_vol_include <- censor_sum_goodruns$n_vol - censor_sum_goodruns$n_censor

# count number of TRs across "good runs" for each subject
TR_count <- censor_sum_goodruns %>% group_by(id) %>% dplyr::summarise(n_vol_goodruns = sum(n_vol_include))

# add TR_count to compiled
compiled<-merge(x=compiled,y=TR_count,by="id",all.x=TRUE)


```

```{r concat dataframes and subset}

# copy 'compiled' to a new dataframe for subsequent steps so that 'compiled' remains untouched

# remove subject 31 from dataframes -- they are inelligible for the study due to ADHD
attended_df <- compiled[! compiled$id == 31, ]

# isolate subjects included in imaging analyses
analyzed_df <- attended_df[attended_df$included == 1, ]

```

# Descriptive statistics

#### Participant count - sections 2.1, 2.4
```{r }

# number of subjects who attended V6 (section 2.1)
nrow(attended_df)

# frequency of children accompanied by mother (0) and father (1); (section 2.1
table(attended_df$parent_respondent)

# number of subjects included in analyses (section 2.1)
sum(attended_df$included == 1)

# number of subjects excluded from analyses (section 2.1)
sum(attended_df$included == 0)

# proportion of maternal BMI method (section 2.4)
prop.table(table(attended_df$mom_bmi_method))

```

#### fMRI exclusion numbers (section 3.3.3)
```{r fmri exclusion rationale }

# frequency of each exclusion rationale
table(attended_df$exc_rationale)

```

#### Demographics by inclusion status
```{r Table S1: demo by inclusion status}

# prepare variables
attended_df$included <- factor(attended_df$included, levels=c(0,1),
         labels=c("Excluded", 
                  "Included"))

attended_df$sex <- factor(attended_df$sex, levels=c(0,1),
                            labels=c("Male", 
                                "Female"))

attended_df$race <- factor(attended_df$race, levels=c(0,1,2,3,4),
                            labels=c("White", 
                                "American Indian/Alaskan Native",
                                "Asian",
                                "Black/African American",
                                "Hawaiian/Pacific Islander"))

attended_df$ethnicity <- factor(attended_df$ethnicity, levels=c(0,1),
                            labels=c("Not Hispanic or Latino", 
                                "Hispanic or Latino"))

attended_df$risk_status_mom <- factor(attended_df$risk_status_mom, levels=c(0,1,2),
                            labels=c("Low", 
                                "High", "Neither"))


# drop unused factor levels (i.e., "Neither" level)
attended_df$risk_status_mom <- droplevels(attended_df$risk_status_mom)

# assign labels for table1()
label(attended_df$sex) <- "Sex"
label(attended_df$race) <- "Race"
label(attended_df$ethnicity) <- "Ethnicity"
label(attended_df$age_yr) <- "Age, yrs"
label(attended_df$income_recode) <- "Family Income"
label(attended_df$mom_edu_recode) <- "Maternal Education"
label(attended_df$bmi_percentile) <- "BMI percentile"
label(attended_df$risk_status_mom) <- "Familial risk status"
label(attended_df$mom_bmi_method) <- "Maternal anthropometrics"
label(attended_df$fmi) <- "Fat mass index"


# generate table: include vs. excluded
table1(~ sex + age_yr + race + ethnicity + income_recode + mom_edu_recode + risk_status_mom + mom_bmi_method + bmi_percentile + fmi| included, data=attended_df)


parentally_reported_maternal_ids <- attended_df$id[attended_df$included == "Included" & attended_df$mom_bmi_method == "reported"]
print(parentally_reported_maternal_ids)
```

```{r compare demo: included vs excluded}

# sex
chisq.test(attended_df$included, attended_df$sex, correct=TRUE)

# risk group
chisq.test(attended_df$included, attended_df$risk_status_mom, correct=TRUE)

# age
t.test(attended_df$age ~ attended_df$included, var.equal = FALSE)

# race
fisher.test(attended_df$included, attended_df$race)

# income
fisher.test(attended_df$included, attended_df$income_recode)

# maternal education
chisq.test(attended_df$included, attended_df$mom_edu_recode, correct=TRUE)

# BMI %tile
t.test(attended_df$bmi_percentile ~ attended_df$included, var.equal = FALSE)

# FMI 
t.test(attended_df$fmi ~ attended_df$included, var.equal = FALSE)


```

#### Demographics and MRI variables by familial risk status

These analyses are restricted to children included in analyses (analyzed_df)

```{r Table 1: demo + MRI variables by risk}

# prepare variables
analyzed_df$included <- factor(analyzed_df$included, levels=c(0,1),
         labels=c("Excluded", 
                  "Included"))

analyzed_df$sex <- factor(analyzed_df$sex, levels=c(0,1),
                            labels=c("Male", 
                                "Female"))

analyzed_df$race <- factor(analyzed_df$race, levels=c(0,1,2,3,4),
                            labels=c("White", 
                                "American Indian/Alaskan Native",
                                "Asian",
                                "Black/African American",
                                "Hawaiian/Pacific Islander"))

analyzed_df$ethnicity <- factor(analyzed_df$ethnicity, levels=c(0,1),
                            labels=c("Not Hispanic or Latino", 
                                "Hispanic or Latino"))


analyzed_df$risk_status_mom <- factor(analyzed_df$risk_status_mom, levels=c(0,1,2),
                            labels=c("Low Risk", 
                                "High Risk", "Neither"))

# drop unused factor levels (i.e., "Neither" level)
analyzed_df$risk_status_mom <- droplevels(analyzed_df$risk_status_mom)

# assign labels for table1()
label(analyzed_df$sex) <- "Sex"
label(analyzed_df$race) <- "Race"
label(analyzed_df$ethnicity) <- "Ethnicity"
label(analyzed_df$age_yr) <- "Age, yrs"
label(analyzed_df$income_recode) <- "Family Income"
label(analyzed_df$mom_edu_recode) <- "Maternal Education"
label(analyzed_df$bmi_percentile) <- "BMI percentile"
label(analyzed_df$risk_status_mom) <- "Familial risk status"
label(analyzed_df$fmi) <- "Fat mass index"
label(analyzed_df$n_run_good) <- "Analyzed runs (n)"
label(analyzed_df$n_vol_goodruns) <- "Analyzed timepoints (n)"
label(analyzed_df$pre_mri_ff) <- "Pre-MRI fullness"
label(analyzed_df$fd_avg_allruns) <- "Average framewise displacement"
label(analyzed_df$cams_pre_mri) <- "Pre-MRI anxiety"
label(analyzed_df$pre_mri_snack) <- "Consumed snack"

# generate table
table1(~ age_yr + bmi_percentile + fmi + sex +  race + ethnicity + income_recode + mom_edu_recode + n_run_good + n_vol_goodruns + fd_avg_allruns + pre_mri_ff + cams_pre_mri + pre_mri_snack | risk_status_mom, data=analyzed_df)

```

```{r compare demo: by risk}

# sex
chisq.test(analyzed_df$risk_status_mom, analyzed_df$sex, correct=TRUE)

# age
t.test(analyzed_df$age ~ analyzed_df$risk_status_mom, var.equal = FALSE)

# race
fisher.test(analyzed_df$risk_status_mom, analyzed_df$race)

# income
fisher.test(analyzed_df$risk_status_mom, analyzed_df$income_recode)

# maternal education
fisher.test(analyzed_df$risk_status_mom, analyzed_df$mom_edu_recode)

# BMI %tile
t.test(analyzed_df$bmi_percentile ~ analyzed_df$risk_status_mom, var.equal = FALSE)

# FMI 
t.test(analyzed_df$fmi ~ analyzed_df$risk_status_mom, var.equal = FALSE)

```

```{r compare MRI: by risk age and sex}

# by age
cor.test(analyzed_df$age, analyzed_df$n_run_good, method=c("pearson"))
cor.test(analyzed_df$age, analyzed_df$n_vol_goodruns, method=c("pearson"))
cor.test(analyzed_df$age, analyzed_df$fd_avg_allruns, method=c("pearson"))
cor.test(analyzed_df$age, analyzed_df$pre_mri_ff, method=c("pearson"))
cor.test(analyzed_df$age, analyzed_df$cams_pre_mri, method=c("pearson"))
t.test(analyzed_df$age ~ analyzed_df$pre_mri_snack, var.equal = FALSE)


# by sex
t.test(analyzed_df$n_run_good ~ analyzed_df$sex, var.equal = FALSE)
t.test(analyzed_df$n_vol_goodruns ~ analyzed_df$sex, var.equal = FALSE)
t.test(analyzed_df$fd_avg_allruns ~ analyzed_df$sex, var.equal = FALSE)
t.test(analyzed_df$pre_mri_ff ~ analyzed_df$sex, var.equal = FALSE)
t.test(analyzed_df$cams_pre_mri ~ analyzed_df$sex, var.equal = FALSE)
chisq.test(analyzed_df$pre_mri_snack, analyzed_df$sex, correct=TRUE)

# frequency table for snack consumption by sex
analyzed_df %>%
  group_by(sex,pre_mri_snack) %>%
  summarize(Freq=n())

# by risk
t.test(analyzed_df$n_run_good ~ analyzed_df$risk_status_mom, var.equal = FALSE)
t.test(analyzed_df$n_vol_goodruns ~ analyzed_df$risk_status_mom, var.equal = FALSE)
t.test(analyzed_df$fd_avg_allruns ~ analyzed_df$risk_status_mom, var.equal = FALSE)
t.test(analyzed_df$pre_mri_ff ~ analyzed_df$risk_status_mom, var.equal = FALSE)
t.test(analyzed_df$cams_pre_mri ~ analyzed_df$risk_status_mom, var.equal = FALSE)
chisq.test(analyzed_df$pre_mri_snack, analyzed_df$risk_status_mom, correct=TRUE)

# frequency table for snack consumption by risk_status_mom
analyzed_df %>%
  group_by(risk_status_mom,pre_mri_snack) %>%
  summarize(Freq=n())
```
